export * from './Additive';
export * from './Array';
export * from './Boolean';
export * from './Conj';
export * from './Disj';
export * from './Either';
export * from './First';
export * from './Last';
export * from './Maybe';
export * from './Multiplicative';
export * from './Number';
export * from './String';
export { liftA1 } from './typeclasses/Applicative';
export { lift2, lift3, lift4, lift5 } from './typeclasses/Apply';
export { join } from './typeclasses/Bind';
export { fold } from './typeclasses/Foldable';
export { flap, mapTo } from './typeclasses/Functor';
export { ap, liftM1 } from './typeclasses/Monad';
